/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m;

import Fuentes.fuente;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *CLASE DE LA INTERFAZ DEL MINI MAPA DE LA EMPRESA
 * @author gabriel
 */
public class map extends javax.swing.JFrame {

 //CREANDO OBJETO DE LA CLASE FUENTE Y TIMER
     fuente obj= new fuente();
     Timer  d =new Timer();
    
     //CONSTRUCTOR
     public map() {
        initComponents();
        //En el centro
        this.setLocationRelativeTo(null);
        //Titulo de la interfaz
        this.setTitle("monitor Beta");
      
        
        //ACTUALIZACION DE LAS IPS PUBLICAS Y PRIVADA CADA 1 SEGUNDO
          TimerTask j = new TimerTask() {

         @Override
         public void run() {
              try {
            obj.iplocal();
            obj.ippublica();
        
           
        } catch (IOException ex) {
            Logger.getLogger(map.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         }
     };
         d.schedule(j, 0, 1000);
        
        
        
        
    }//LLAVE DE CIERE DEL CONSTRUCTOR


  // Object a[]={gateway,torre1,torre2,torre3};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        torre1 = new javax.swing.JButton();
        torre2 = new javax.swing.JButton();
        torre3 = new javax.swing.JButton();
        torre4 = new javax.swing.JButton();
        torre5 = new javax.swing.JButton();
        torre6 = new javax.swing.JButton();
        torre7 = new javax.swing.JButton();
        torre8 = new javax.swing.JButton();
        tiempo = new javax.swing.JComboBox();
        local = new javax.swing.JTextField();
        privadoo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        registro = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        vinculonodo = new javax.swing.JMenuItem();
        hip = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        torre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre1.setText("Collores");
        torre1.setFocusable(false);
        torre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre1ActionPerformed(evt);
            }
        });

        torre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre2.setText("Hato tejas");
        torre2.setFocusable(false);
        torre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre2ActionPerformed(evt);
            }
        });

        torre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre3.setText("Atalaya");
        torre3.setFocusable(false);
        torre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre3ActionPerformed(evt);
            }
        });

        torre4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre4.setText("Culebras");
        torre4.setFocusable(false);
        torre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre4ActionPerformed(evt);
            }
        });

        torre5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre5.setText("Bayamon");
        torre5.setFocusable(false);
        torre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre5ActionPerformed(evt);
            }
        });

        torre6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre6.setText("Masas");
        torre6.setFocusable(false);
        torre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre6ActionPerformed(evt);
            }
        });

        torre7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre7.setText("MDE");
        torre7.setFocusable(false);
        torre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre7ActionPerformed(evt);
            }
        });

        torre8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/router-wifi.png"))); // NOI18N
        torre8.setText("Cubuy");
        torre8.setFocusable(false);
        torre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre8ActionPerformed(evt);
            }
        });

        tiempo.setBackground(new java.awt.Color(0, 102, 255));
        tiempo.setForeground(new java.awt.Color(1, 27, 45));
        tiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 segundos", "30 segundos", "1 minuto", "5 minutos", "10 minutos" }));
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });

        local.setEditable(false);
        local.setBackground(new java.awt.Color(0, 0, 0));
        local.setForeground(new java.awt.Color(0, 255, 255));
        local.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        local.setBorder(null);
        local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localActionPerformed(evt);
            }
        });

        privadoo.setEditable(false);
        privadoo.setBackground(new java.awt.Color(0, 0, 0));
        privadoo.setForeground(new java.awt.Color(0, 255, 255));
        privadoo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        privadoo.setBorder(null);
        privadoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privadooActionPerformed(evt);
            }
        });

        registro.setBackground(new java.awt.Color(0, 0, 0));
        registro.setColumns(20);
        registro.setForeground(new java.awt.Color(255, 0, 0));
        registro.setRows(5);
        registro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        jScrollPane1.setViewportView(registro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(local, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(privadoo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(torre5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(torre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(torre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(torre6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(torre7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(torre3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(torre8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(torre4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(local, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(privadoo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(torre1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torre2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torre3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torre4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(torre5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torre6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torre7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torre8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setBorderPainted(false);

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setForeground(new java.awt.Color(255, 102, 51));
        jMenu1.setText("Otras Herramientas");

        jMenuItem1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setForeground(new java.awt.Color(0, 204, 204));
        jMenuItem1.setText("Visitas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        vinculonodo.setBackground(new java.awt.Color(51, 51, 51));
        vinculonodo.setForeground(new java.awt.Color(0, 204, 204));
        vinculonodo.setText("Nodo");
        vinculonodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinculonodoActionPerformed(evt);
            }
        });
        jMenu1.add(vinculonodo);

        hip.setBackground(new java.awt.Color(51, 51, 51));
        hip.setForeground(new java.awt.Color(0, 204, 204));
        hip.setText("Host Ip");
        hip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipActionPerformed(evt);
            }
        });
        jMenu1.add(hip);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
     //COMBO BOX
        
        Timer t=new Timer();
        
        //5 segundos 
         if(tiempo.getSelectedIndex()==0){
        
        
        TimerTask s=new TimerTask() {

            @Override
            public void run() {
               
                    
          //   obj.pingazo("192.168.1.1", (map) a[0]);   
      
        obj.pingazo("10.255.255.16", torre1,"collores");
        obj.pingazo("10.255.255.162", torre2,"hato tejas");
        obj.pingazo("10.255.255.66", torre3,"atalaya");
        obj.pingazo("10.255.255.206", torre4,"culebras");
        obj.pingazo("10.255.255.6", torre5,"bayamon");
        obj.pingazo("10.255.255.18", torre6,"masas");
        obj.pingazo("10.255.255.65", torre7,"mde");
        obj.pingazo("10.255.255.19", torre8,"cubuy");
  
            }
        };
        
        t.schedule(s, 0, 5000);
        
        }
        
                
        //30 segundos
        if(tiempo.getSelectedIndex()==1){
        
        
        TimerTask s=new TimerTask() {

            @Override
            public void run() {
               
                
 
        obj.pingazo("10.255.255.16", torre1,"collores");
        obj.pingazo("10.255.255.162", torre2,"hato tejas");
        obj.pingazo("10.255.255.66", torre3,"atalaya");
        obj.pingazo("10.255.255.206", torre4,"culebras");
        obj.pingazo("10.255.255.6", torre5,"bayamon");
        obj.pingazo("10.255.255.18", torre6,"masas");
        obj.pingazo("10.255.255.65", torre7,"mde");
        obj.pingazo("10.255.255.19", torre8,"cubuy");
                
            }
        };
        
        t.schedule(s, 0, 30000);
        
        }
       
        //1 minuto
          if(tiempo.getSelectedIndex()==2){
        
        
        TimerTask s=new TimerTask() {

            @Override
            public void run() {
           
        obj.pingazo("10.255.255.16", torre1,"collores");
        obj.pingazo("10.255.255.162", torre2,"hato tejas");
        obj.pingazo("10.255.255.66", torre3,"atalaya");
        obj.pingazo("10.255.255.206", torre4,"culebras");
        obj.pingazo("10.255.255.6", torre5,"bayamon");
        obj.pingazo("10.255.255.18", torre6,"masas");
        obj.pingazo("10.255.255.65", torre7,"mde");
        obj.pingazo("10.255.255.19", torre8,"cubuy");
            }
        };
        
        t.schedule(s, 0, 60000);
        
        }
        
          //5 minutos
               if(tiempo.getSelectedIndex()==3){
        
        
        TimerTask s=new TimerTask() {

            @Override
            public void run() {
               
      
        obj.pingazo("10.255.255.16", torre1,"collores");
        obj.pingazo("10.255.255.162", torre2,"hato tejas");
        obj.pingazo("10.255.255.66", torre3,"atalaya");
        obj.pingazo("10.255.255.206", torre4,"culebras");
        obj.pingazo("10.255.255.6", torre5,"bayamon");
        obj.pingazo("10.255.255.18", torre6,"masas");
        obj.pingazo("10.255.255.65", torre7,"mde");
        obj.pingazo("10.255.255.19", torre8,"cubuy");
                
                
            }
        };
        
        t.schedule(s, 0, 300000);
        
        }
          
          //10 minutos
                    if(tiempo.getSelectedIndex()==4){
        
        
        TimerTask s=new TimerTask() {

            @Override
            public void run() {
      
        obj.pingazo("10.255.255.16", torre1,"collores");
        obj.pingazo("10.255.255.162", torre2,"hato tejas");
        obj.pingazo("10.255.255.66", torre3,"atalaya");
        obj.pingazo("10.255.255.206", torre4,"culebras");
        obj.pingazo("10.255.255.6", torre5,"bayamon");
        obj.pingazo("10.255.255.18", torre6,"masas");
        obj.pingazo("10.255.255.65", torre7,"mde");
        obj.pingazo("10.255.255.19", torre8,"cubuy");
                
                
            }
        };
        
        t.schedule(s, 0, 600000);
        
        }
               
               
    }//GEN-LAST:event_tiempoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
this.dispose();
       // visitas s=new visitas();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localActionPerformed
    
    }//GEN-LAST:event_localActionPerformed

    private void privadooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privadooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privadooActionPerformed

    private void torre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre1ActionPerformed
      JOptionPane.showMessageDialog(null, "La ip es 10.255.255.16");
    }//GEN-LAST:event_torre1ActionPerformed

    private void vinculonodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinculonodoActionPerformed
     
        String nombre_nodo=JOptionPane.showInputDialog("Por favor indique el nombre del nodo");
        
         String address=JOptionPane.showInputDialog("Ip Address:");
        
        
       // Nodo nodo =new Nodo(nombre_nodo,address);
      
        
       
        
    }//GEN-LAST:event_vinculonodoActionPerformed

    private void hipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipActionPerformed
saberiponombre x= new saberiponombre();
x.setVisible(true);
x.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_hipActionPerformed

    private void torre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre2ActionPerformed
JOptionPane.showMessageDialog(null, "La ip es 10.255.255.162");        // TODO add your handling code here:
    }//GEN-LAST:event_torre2ActionPerformed

    private void torre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre3ActionPerformed
   JOptionPane.showMessageDialog(null, "La ip es 10.255.255.66");         // TODO add your handling code here:10.255.255.66
    }//GEN-LAST:event_torre3ActionPerformed

    private void torre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre4ActionPerformed
    JOptionPane.showMessageDialog(null, "La ip es 10.255.255.206");      // TODO add your handling code here:
    }//GEN-LAST:event_torre4ActionPerformed

    private void torre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre5ActionPerformed
   JOptionPane.showMessageDialog(null, "La ip es  10.255.255.6");  // TODO add your handling code here:
    }//GEN-LAST:event_torre5ActionPerformed

    private void torre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre6ActionPerformed
     JOptionPane.showMessageDialog(null, "La ip es  10.255.255.18");    // TODO add your handling code here:
    }//GEN-LAST:event_torre6ActionPerformed

    private void torre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre7ActionPerformed
      JOptionPane.showMessageDialog(null, "La ip es  10.255.255.65");      // TODO add your handling code here:
    }//GEN-LAST:event_torre7ActionPerformed

    private void torre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre8ActionPerformed
      JOptionPane.showMessageDialog(null, "La ip es  10.255.255.19");   // TODO add your handling code here:
    }//GEN-LAST:event_torre8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem hip;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField local;
    public static javax.swing.JTextField privadoo;
    public static javax.swing.JTextArea registro;
    public static javax.swing.JComboBox tiempo;
    public static javax.swing.JButton torre1;
    public static javax.swing.JButton torre2;
    public static javax.swing.JButton torre3;
    public static javax.swing.JButton torre4;
    public static javax.swing.JButton torre5;
    public static javax.swing.JButton torre6;
    public static javax.swing.JButton torre7;
    public static javax.swing.JButton torre8;
    public static javax.swing.JMenuItem vinculonodo;
    // End of variables declaration//GEN-END:variables
}
